apiVersion: v1
kind: Service
metadata:
  name: order-app-service
spec:
  type: LoadBalancer  # Сервис будет доступен через внешний IP
  selector:
    app: order-app
  ports:
    - protocol: TCP
      port: 80  # Внешний порт для доступа
      targetPort: 80  # Порт, на котором работает Flask внутри контейнера
  sessionAffinity: None
